// src/lib/blob-download.ts
//
// Client-side Blob download helper (Req 6.1 reports download). Builds an
// in-memory text Blob and triggers a browser download via createObjectURL —
// no fetch, no network, no server. Guarded for SSR / unsupported environments.

/**
 * Trigger a client-side download of `content` as `filename`. Returns true when
 * the download was triggered, false when the environment cannot support it
 * (e.g. server render). Revokes the object URL after triggering.
 */
export function downloadTextAsFile(
  filename: string,
  content: string,
  mimeType = 'text/plain;charset=utf-8',
): boolean {
  if (
    typeof window === 'undefined' ||
    typeof URL === 'undefined' ||
    typeof URL.createObjectURL !== 'function' ||
    typeof document === 'undefined'
  ) {
    return false;
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
  return true;
}

/** Build a simple placeholder document body for an illustrative report. */
export function buildPlaceholderDocument(title: string, lines: string[]): string {
  const header = `${title}\n${'='.repeat(title.length)}\n\n`;
  const body = lines.join('\n');
  const footer =
    '\n\nThis is an illustrative placeholder document generated by the KITE portal preview. ' +
    'It does not contain official data. For verified publications, visit eitbt.karnataka.gov.in/startup.';
  return header + body + footer;
}
